In [1]:
# import required libraries
import numpy as np
import pandas as pd

In [2]:
# Reading Dataset
df=pd.read_csv('50_Startups.csv')

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.shape

(50, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [7]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [9]:
df['State']=le.fit_transform(df.State)

In [10]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [11]:
X=df.iloc[:,:-1].values

In [12]:
y=df.iloc[:,4:5].values

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=0)

In [14]:
x_train.shape, x_test.shape

((35, 4), (15, 4))

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [16]:
# Creatinh ANN Seklton
regressor=Sequential()  #initialising the Model
regressor.add(Dense(4, activation='relu')) # input layer
regressor.add(Dense(8, activation='relu'))
regressor.add(Dense(16, activation='relu'))  
regressor.add(Dense(1, activation='linear')) # Output layer

In [17]:
# Compiling ANN model
regressor.compile(loss='mse',optimizer='adam',metrics=['mse'])

In [18]:
# Training the Model
regressor.fit(x_train,y_train, batch_size=10, epochs=300)

Epoch 1/300


4/4 [==============================] - 2s 8ms/step - loss: 12612386816.0000 - mse: 12612386816.0000
Epoch 2/300
4/4 [==============================] - 0s 6ms/step - loss: 12058977280.0000 - mse: 12058977280.0000
Epoch 3/300
4/4 [==============================] - 0s 5ms/step - loss: 11572050944.0000 - mse: 11572050944.0000
Epoch 4/300
4/4 [==============================] - 0s 7ms/step - loss: 11004905472.0000 - mse: 11004905472.0000
Epoch 5/300
4/4 [==============================] - 0s 5ms/step - loss: 10470678528.0000 - mse: 10470678528.0000
Epoch 6/300
4/4 [==============================] - 0s 4ms/step - loss: 9957249024.0000 - mse: 9957249024.0000
Epoch 7/300
4/4 [==============================] - 0s 6ms/step - loss: 9476130816.0000 - mse: 9476129792.0000
Epoch 8/300
4/4 [==============================] - 0s 6ms/step - loss: 8981497856.0000 - mse: 8981498880.0000
Epoch 9/300
4/4 [==============================] - 0s 6ms/step - loss: 8460073984.0000 - mse: 8460073984.000

4/4 [==============================] - 0s 5ms/step - loss: 468181408.0000 - mse: 468181408.0000
Epoch 72/300
4/4 [==============================] - 0s 5ms/step - loss: 465172096.0000 - mse: 465172096.0000
Epoch 73/300
4/4 [==============================] - 0s 5ms/step - loss: 460616384.0000 - mse: 460616384.0000
Epoch 74/300
4/4 [==============================] - 0s 5ms/step - loss: 457266048.0000 - mse: 457266048.0000
Epoch 75/300
4/4 [==============================] - 0s 5ms/step - loss: 453654176.0000 - mse: 453654176.0000
Epoch 76/300
4/4 [==============================] - 0s 5ms/step - loss: 449332192.0000 - mse: 449332192.0000
Epoch 77/300
4/4 [==============================] - 0s 7ms/step - loss: 445979520.0000 - mse: 445979520.0000
Epoch 78/300
4/4 [==============================] - 0s 5ms/step - loss: 441995808.0000 - mse: 441995808.0000
Epoch 79/300
4/4 [==============================] - 0s 6ms/step - loss: 439365344.0000 - mse: 439365344.0000
Epoch 80/300
4/4 [==============

4/4 [==============================] - 0s 5ms/step - loss: 296169152.0000 - mse: 296169152.0000
Epoch 146/300
4/4 [==============================] - 0s 5ms/step - loss: 295236768.0000 - mse: 295236768.0000
Epoch 147/300
4/4 [==============================] - 0s 4ms/step - loss: 294056096.0000 - mse: 294056096.0000
Epoch 148/300
4/4 [==============================] - 0s 6ms/step - loss: 293376416.0000 - mse: 293376416.0000
Epoch 149/300
4/4 [==============================] - 0s 5ms/step - loss: 291744000.0000 - mse: 291744000.0000
Epoch 150/300
4/4 [==============================] - 0s 6ms/step - loss: 290499200.0000 - mse: 290499168.0000
Epoch 151/300
4/4 [==============================] - 0s 6ms/step - loss: 288956160.0000 - mse: 288956160.0000
Epoch 152/300
4/4 [==============================] - 0s 6ms/step - loss: 287689856.0000 - mse: 287689856.0000
Epoch 153/300
4/4 [==============================] - 0s 5ms/step - loss: 286475520.0000 - mse: 286475520.0000
Epoch 154/300
4/4 [=====

4/4 [==============================] - 0s 5ms/step - loss: 197013296.0000 - mse: 197013296.0000
Epoch 220/300
4/4 [==============================] - 0s 5ms/step - loss: 195874704.0000 - mse: 195874704.0000
Epoch 221/300
4/4 [==============================] - 0s 6ms/step - loss: 194615088.0000 - mse: 194615088.0000
Epoch 222/300
4/4 [==============================] - 0s 5ms/step - loss: 193294304.0000 - mse: 193294304.0000
Epoch 223/300
4/4 [==============================] - 0s 5ms/step - loss: 192617712.0000 - mse: 192617712.0000
Epoch 224/300
4/4 [==============================] - 0s 5ms/step - loss: 190998800.0000 - mse: 190998800.0000
Epoch 225/300
4/4 [==============================] - 0s 6ms/step - loss: 189832560.0000 - mse: 189832560.0000
Epoch 226/300
4/4 [==============================] - 0s 5ms/step - loss: 188915456.0000 - mse: 188915456.0000
Epoch 227/300
4/4 [==============================] - 0s 5ms/step - loss: 187523408.0000 - mse: 187523408.0000
Epoch 228/300
4/4 [=====

4/4 [==============================] - 0s 4ms/step - loss: 155634352.0000 - mse: 155634352.0000
Epoch 294/300
4/4 [==============================] - 0s 4ms/step - loss: 155414736.0000 - mse: 155414736.0000
Epoch 295/300
4/4 [==============================] - 0s 4ms/step - loss: 155350352.0000 - mse: 155350352.0000
Epoch 296/300
4/4 [==============================] - 0s 6ms/step - loss: 154588224.0000 - mse: 154588224.0000
Epoch 297/300
4/4 [==============================] - 0s 5ms/step - loss: 154257648.0000 - mse: 154257648.0000
Epoch 298/300
4/4 [==============================] - 0s 6ms/step - loss: 154967072.0000 - mse: 154967056.0000
Epoch 299/300
4/4 [==============================] - 0s 8ms/step - loss: 153998096.0000 - mse: 153998096.0000
Epoch 300/300
4/4 [==============================] - 0s 5ms/step - loss: 153716768.0000 - mse: 153716768.0000


In [19]:
# test the model
y_pred=regressor.predict(x_test)
y_pred

1/1 [==============================] - 0s 180ms/step


array([[125972.1  ],
       [119240.24 ],
       [119511.59 ],
       [ 63539.316],
       [183550.31 ],
       [123636.18 ],
       [ 53767.402],
       [107961.62 ],
       [116027.305],
       [167627.34 ],
       [ 88652.65 ],
       [ 76401.81 ],
       [117229.39 ],
       [112497.5  ],
       [124161.11 ]], dtype=float32)

In [20]:
from sklearn.metrics import r2_score

In [21]:
r2_score(y_test,y_pred)

0.7096316815700991

In [23]:
y_pred.flatten()

array([125972.1  , 119240.24 , 119511.59 ,  63539.316, 183550.31 ,
       123636.18 ,  53767.402, 107961.62 , 116027.305, 167627.34 ,
        88652.65 ,  76401.81 , 117229.39 , 112497.5  , 124161.11 ],
      dtype=float32)

In [24]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [25]:
# testing with random values
regressor.predict([[142107,9138,12335,2]])

1/1 [==============================] - 0s 194ms/step


array([[92108.516]], dtype=float32)