In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          225     Spain  Female   41   
2          3    15619304      Onio          629    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
dataset['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [7]:
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13:14].values

In [8]:

x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [225, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [629, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [11]:
x.shape

(10000, 10)

In [12]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[1,2])],remainder='passthrough')
x=ct.fit_transform(x)

In [13]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
x.shape

(10000, 13)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sa=StandardScaler()


In [17]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [18]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [19]:
from tensorflow.keras.models import Sequential
from keras.layers import Dense

In [20]:
model=Sequential()

In [21]:
x.shape

(10000, 13)

In [22]:
model.add(Dense(units=13,activation='relu',kernel_initializer='random_uniform'))

In [23]:
model.add(Dense(units=26,activation='relu',kernel_initializer='random_uniform'))

In [24]:
model.add(Dense(units=26,activation='relu',kernel_initializer='random_uniform'))

In [25]:
model.add(Dense(units=1,activation='sigmoid',kernel_initializer='random_uniform'))

In [26]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [27]:
model.fit(x_train,y_train,batch_size=32,epochs=20)

Epoch 1/20


250/250 [==============================] - 2s 2ms/step - loss: 0.4981 - accuracy: 0.7955
Epoch 2/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4297 - accuracy: 0.7960
Epoch 3/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4240 - accuracy: 0.7960
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4205 - accuracy: 0.8105
Epoch 5/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4177 - accuracy: 0.8274
Epoch 6/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4153 - accuracy: 0.8313
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4139 - accuracy: 0.8347
Epoch 8/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4121 - accuracy: 0.8321
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4109 - accuracy: 0.8336
Epoch 10/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4094 - accuracy: 0.83

In [28]:
ypred=model.predict(x_test)

63/63 [==============================] - 0s 2ms/step


In [29]:
ypred

array([[0.22229771],
       [0.27306837],
       [0.1284572 ],
       ...,
       [0.18978292],
       [0.12795714],
       [0.1598218 ]], dtype=float32)

In [30]:
ypred=ypred>0.5
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [31]:
y_test

array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [32]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [33]:
x.shape

(10000, 13)

In [34]:
x[0]

array([1.0, 0.0, 0.0, 1.0, 0.0, 619, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [35]:
y_s=model.predict([[1.0, 0.0, 0.0, 1.0, 0.0, 619, 42, 2, 0.0, 1, 1, 1, 101348.88]])

1/1 [==============================] - 0s 43ms/step


In [36]:
y_s

array([[0.]], dtype=float32)

In [37]:
p=np.array(sc.transform(ct.transform([[875,'France','Female',42,5,1234,0,1,1,1234567]])))

In [38]:
p

array([[ 1.04501206, -0.61433742, -0.57427105,  1.11339196, -1.11339196,
         2.35839422,  0.26349271, -0.04867536, -1.24761801, -2.54811601,
         0.66011376,  0.97628121, 19.77099386]])

In [39]:
yp=model.predict(p)

1/1 [==============================] - 0s 36ms/step


In [40]:
yp

array([[0.00428867]], dtype=float32)

In [41]:
yp=yp>0.5
yp

array([[False]])