# TensorFlow basics

TensorFlow is an end-to-end platform for machine learning. It supports the following:

* Multidimensional-array based numeric computation (similar to <a href="https://numpy.org/" class="external">NumPy</a>.)
* GPU and distributed processing
* Automatic differentiation
* Model construction, training, and export
* And more

## Tensors (Constant)

TensorFlow operates on multidimensional arrays or _tensors_ represented as `tf.Tensor` objects. Here is a two-dimensional tensor:

The most important attributes of a `tf.Tensor` are its `shape` and `dtype`:

* `Tensor.shape`: tells you the size of the tensor along each of its axes.
* `Tensor.dtype`: tells you the type of all the elements in the tensor.

In [1]:
pip install --upgrade pip

   ---------------------------------------- 2.1/2.1 MB 1.9 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.3.2
    Uninstalling pip-23.3.2:
      Successfully uninstalled pip-23.3.2
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow as tf

C:\Users\indra\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
''' A scalar, in the context of tensors, refers to a single value, which can be represented 
as a tensor with zero dimensions. Essentially, a scalar is a rank-0 tens '''
#Here is a "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".

Scalar_tensor = tf.constant(4)
print(Scalar_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
'''In the context of tensors, a vector refers to a one-dimensional array of elements. 
It's  a list of numbers arranged in a single dimension'''
# Vectors are represented as tensors with a rank of 1.
# A "vector" or "rank-1" tensor is like a list of values. A vector has one axis.

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [7]:
'''In TensorFlow, matrices are multi-dimensional arrays that can hold 
numerical data. They are represented as tensors with two dimensions.'''
# A "matrix" or "rank-2" tensor has two axes.

rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [3]:
# Tensors may have more axes; here is a tensor with three axes

rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [9]:
import numpy as np

# You can convert a tensor to a NumPy array


np.array(rank_3_tensor)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [2]:
import tensorflow as tf

tensor_1 = tf.constant([[1, 2.3, 3.],
                 [4, 5, 6]])

print(tensor_1)
print(tensor_1.shape)
print(tensor_1.dtype)

tf.Tensor(
[[1.  2.3 3. ]
 [4.  5.  6. ]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [6]:
tensor_2 = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

print(tensor_2)
print(tensor_2.shape)
print(tensor_2.dtype)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
<dtype: 'int32'>


In [4]:
tensor_3 = tf.constant([[15, 23, 3],
                 [4, 5, 6]],dtype=tf.float32)

print(tensor_3)
print(tensor_3.shape)
print(tensor_3.dtype)

tf.Tensor(
[[15. 23.  3.]
 [ 4.  5.  6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


TensorFlow implements standard mathematical operations on tensors, as well as many operations specialized for machine learning.

For example:

In [7]:
tensor_1 + tensor_3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[16. , 25.3,  6. ],
       [ 8. , 10. , 12. ]], dtype=float32)>

In [18]:
print(tensor_1)

tf.Tensor(
[[1.  2.3 3. ]
 [4.  5.  6. ]], shape=(2, 3), dtype=float32)


In [14]:
5 * tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5. , 11.5, 15. ],
       [20. , 25. , 30. ]], dtype=float32)>

In [19]:
tf.transpose(tensor_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1. , 4. ],
       [2.3, 5. ],
       [3. , 6. ]], dtype=float32)>

In [10]:
tensor_1 @ tf.transpose(tensor_1)  # Matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[15.29, 33.5 ],
       [33.5 , 77.  ]], dtype=float32)>

In [21]:
tf.matmul(tensor_1, tf.transpose(tensor_1))  # Another way of Matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[15.29, 33.5 ],
       [33.5 , 77.  ]], dtype=float32)>

In [22]:
tf.concat([tensor_1, tensor_3], axis=0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1. ,  2.3,  3. ],
       [ 4. ,  5. ,  6. ],
       [15. , 23. ,  3. ],
       [ 4. ,  5. ,  6. ]], dtype=float32)>

In [23]:
tf.nn.softmax(tensor_1, axis=-1)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.08293007, 0.304295  , 0.6127749 ],
       [0.09003057, 0.24472848, 0.6652409 ]], dtype=float32)>

In [4]:
tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]], dtype=float32)>

In [3]:
"""
calculates the sum of all elements in tensor_1. If tensor_1 is a multi-dimensional
tensor, the tf.reduce_sum function will sum across all dimensions, effectively
flattening the tensor.
"""
tf.reduce_sum(tensor_1)

<tf.Tensor: shape=(), dtype=float32, numpy=21.3>

Note: Typically, anywhere a TensorFlow function expects a `Tensor` as input, the function will also accept anything that can be converted to a `Tensor` using `tf.convert_to_tensor`. See below for an example.

In [10]:
'''
The code tf.convert_to_tensor([1, 2, 3]) is a TensorFlow operation that converts a
Python list to a TensorFlow tensor. The resulting tensor will have the same data
type as the elements in the list. In thiscase, since the list contains integers,
the tensor will have the default integer data type, which is tf.int32
'''
aa = tf.convert_to_tensor([1,2,3])
print(aa)
print(aa.dtype)


tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<dtype: 'int32'>


In [12]:
tf.reduce_sum([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

## Variables

Normal `tf.Tensor` objects are immutable. To store model weights (or other mutable state) in TensorFlow use a `tf.Variable`.

In [16]:
var_1 = tf.Variable([0, 1.70, 0])
var_1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0. , 1.7, 0. ], dtype=float32)>

In [ ]:
"""
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0. , 1.7, 0. ],
dtype=float32)>: This line indicates that var_1 is a TensorFlow variable. 
It has a shape of (3,), meaning it's a 1D tensor with three elements. The data type is float32,
and the values are specified in the numpy array as [0. , 1.7, 0.].
"""

In [17]:
var_1.assign([1, 2, 3])
var_1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [22]:
var_1.assign_add([1, 5, 1])
#When you use assign_add() on a TensorFlow variable, 
#it increments the variable by the values provided in the argumen

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([ 5., 22.,  7.], dtype=float32)>

In [23]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [24]:
# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
bool_variable

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False,  True])>

In [25]:
complex_variable = tf.Variable([5 + 4j, 6 + 1j])
complex_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>

In [26]:
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [27]:
print("A variable:", my_variable)
#This line prints the value of the TensorFlow variable my_variable.

print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))
#This line converts the TensorFlow variable my_variable into a 
#TensorFlow tensor using tf.convert_to_tensor and then prints the result.

print("\nIndex of highest value:", tf.math.argmax(my_variable))
#This line calculates the index of the highest value in the TensorFlow 
#variable my_variable using tf.math.argmax and prints the result.


# This creates a new tensor; it  reshape the variable.
print("\nCopying and reshaping: ", tf.reshape(my_variable, [1,4]))

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)

Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [ ]:
#Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)
"""
This represents a tensor with shape (2,), indicating that there are two dimensions.
The values [1, 1] are the indices of the highest values along the specified axis.
"""